input_lvs = [
    {
        'X': (0, 1.01, 0.01),
        'name': 'Experience',
        'terms': {
            'Without experience': ('trimf', 0, 0, 0.067),
            'Minimum experience': ('trapmf', 0, 0.067, 0.134, 0.201),
            'Average experience': ('trapmf', 0.134, 0.201, 0.335, 0.402),
            'Significant experience': ('trapmf', 0.268, 0.402, 0.536, 0.67),
            'Advanced experience': ('trapmf', 0.536, 0.67, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Avg diploma score',
        'terms': {
            'Satisfactorily': ('trapmf', 0, 0, 0.25, 0.5),
            'Good': ('trapmf', 0.25, 0.375, 0.625, 0.75),
            'Excellent': ('trapmf', 0.5, 0.75, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Professional test score',
        'terms': {
            'Low score': ('trapmf', 0, 0, 0.3, 0.5),
            'Medium score': ('trapmf', 0.3, 0.4, 0.6, 0.7),
            'High score': ('trapmf', 0.5, 0.7, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'English test score',
        'terms': {
            'Basic': ('trapmf', 0, 0, 0.2, 0.4),
            'Pre-Intermediate': ('trapmf', 0.2, 0.3, 0.4, 0.5),
            'Intermediate': ('trimf', 0.4, 0.5, 0.6),
            'Upper-Intermediate': ('trapmf', 0.5, 0.6, 0.7, 0.8),
            'Advanced': ('trapmf', 0.6, 0.8, 1, 1),
        }
    }
]

output_lv = {
    'X': (0, 1.01, 0.01),
    'name': 'Candidate suitability',
    'terms': {
        'Not suitable': ('trapmf', 0, 0, 0.1, 0.2),
        'Unlikely suitable': ('trimf', 0, 0.2, 0.4),
        'Partially suitable': ('trapmf', 0.2, 0.3, 0.6, 0.7),
        'Probably suitable': ('trapmf', 0.5, 0.7, 0.8, 0.9),
        'Excellent suitable': ('trapmf', 0.7, 0.9, 1, 1),
    }
}

rule_base = [
    (('Without experience', 'Satisfactorily', 'Low score', 'Basic'), 'Not suitable'),
    (('Without experience', 'Satisfactorily', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
    (('Without experience', 'Satisfactorily', 'Low score', 'Intermediate'), 'Unlikely suitable'),
    (('Without experience', 'Satisfactorily', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'Medium score', 'Basic'), 'Unlikely suitable'),
    (('Without experience', 'Satisfactorily', 'Medium score', 'Pre-Intermediate'), 'Unlikely suitable'),
    (('Without experience', 'Satisfactorily', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'High score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Satisfactorily', 'High score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Good', 'Low score', 'Basic'), 'Unlikely suitable'),
    (('Without experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
    (('Without experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Good', 'High score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Without experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Without experience', 'Excellent', 'High score', 'Advanced'), 'Probably suitable'),
    (('Minimum experience', 'Satisfactorily', 'Low score', 'Basic'), 'Unlikely suitable'),
    (('Minimum experience', 'Satisfactorily', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
    (('Minimum experience', 'Satisfactorily', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'High score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Satisfactorily', 'High score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Low score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
    (('Minimum experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Minimum experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Minimum experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
    (('Minimum experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Minimum experience', 'Excellent', 'High score', 'Advanced'), 'Probably suitable'),
    (('Average experience', 'Satisfactorily', 'Low score', 'Basic'), 'Unlikely suitable'),
    (('Average experience', 'Satisfactorily', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'High score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Satisfactorily', 'High score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Good', 'Low score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Average experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
    (('Average experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Average experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
    (('Significant experience', 'Satisfactorily', 'Low score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'High score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Satisfactorily', 'High score', 'Advanced'), 'Probably suitable'),
    (('Significant experience', 'Good', 'Low score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Significant experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Good', 'High score', 'Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Low score', 'Advanced'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Significant experience', 'Excellent', 'Medium score', 'Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'High score', 'Basic'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Significant experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
    (('Advanced experience', 'Satisfactorily', 'Low score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'Medium score', 'Advanced'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'High score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'High score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Satisfactorily', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Satisfactorily', 'High score', 'Advanced'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'Low score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Good', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'High score', 'Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
    (('Advanced experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Low score', 'Advanced'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
    (('Advanced experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Medium score', 'Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'High score', 'Basic'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
    (('Advanced experience', 'Excellent', 'High score', 'Intermediate'), 'Excellent suitable'),
    (('Advanced experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Excellent suitable'),
    (('Advanced experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
]
